### ISSUE TITLE
Question: Can mjson+jsonpath be done streaming?

### ISSUE THREAD

**Issue by hansbogert** [cesanta/mjson#14]
Does mjson allow streaming jsonpath queries? I.e., can it use constant memory even for very large json documents?

**Comment by cpq** [comment]
mjson already uses constant memory with no allocations for very large documents.

By streaming it is usually assumed that the document can be fed by chunks. Currently, mjson API expects the whole document to reside in memory - so the answer is no.

If the question is "can it be modified to support streaming" - yes it can, since it uses a state machine. That would significantly complicated the API.

**Comment by hansbogert** [comment]
Thank you for answering

However I read the following 2 sentences as contradicting:

> mjson already uses constant memory with no allocations for very large documents.

and

> By streaming it is usually assumed that the document can be fed by chunks. Currently, mjson API expects the whole document to reside in memory - so the answer is no.

how can mjson use constant memory, but it needs the whole document to  be in memory? For example, if I read statement 2, a 1 kB document needs an internal representation of 1kB, and a 1MB document needs 1MB of internal representation, but that is not a constant memory usage, right?
